
version: '3'

services:
  web:
    container_name: booknos_web
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
  app:
    container_name: booknos_app
    build:
      context: .
      dockerfile: ./app/main/Dockerfile
    expose:
      - 5000
    volumes:
      - ./app:/var/www/app
    environment:
      TZ: Asia/Tokyo
      FLASK_ENV: development
      FLASK_APP: __init__.py
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
    links:
      - db
  # db:
  #   container_name: booknos_db
  #   build:
  #     context: .
  #     dockerfile: ./db/Dockerfile
  #   volumes:
  #     - ./db/mysql:/var/lib/mysql
  #     - ./db/logs/mysql:/var/log/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: booknos
  #     MYSQL_DATABASE: booknos
  #     MYSQL_USER: booknos
  #     MYSQL_PASSWORD: booknos
  #     TZ: 'Asia/Tokyo'
  #   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #   ports:
  #     - 3306:3306
