
version: '3'

services:
  web:
    container_name: booknos_web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
  app:
    container_name: booknos_app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    expose:
      - 5000
    volumes:
      - ./app:/var/www/app
    environment:
      TZ: Asia/Tokyo
      FLASK_ENV: development
      FLASK_APP: 'app.app:create_app("local")'
      MYSQL_DATABASE: booknos
      MYSQL_USER: booknos
      MYSQL_PASSWORD: booknos
    links:
      - db
  db:
    container_name: booknos_db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./db/logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: booknos
      MYSQL_DATABASE: booknos
      MYSQL_USER: booknos
      MYSQL_PASSWORD: booknos
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
